seed: 1234
dataset: "planning-datasets/data/mpd/mazes_032_moore_c8"
logdir: "model"
Tmax: 0.25

unet:
  model_type: "baseline"
  target_channels: 1
  base_channels: 64
  time_emb_dim: 256
  channel_mults: [1, 2, 4, 8]

diffusion:
  num_steps: 100
  beta_schedule: "cosine"
  clip_sample: True
  trajectory_sigma: 1.0
  start_goal_sigma: 1.0

params:
  batch_size: 100
  num_epochs: 500
  lr: 0.0001
  limit_train_batches: null
  limit_val_batches: null

checkpoint:
  monitor: "metrics/h_mean"
  mode: "max"
  save_top_k: 1
  save_last: True

early_stop:
  enabled: True
  monitor: "metrics/val_diffusion_loss"
  mode: "min"
  patience: 80
  min_delta: 0.0001

trainer:
  devices: null
  strategy: null
  precision: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 1
  accumulate_grad_batches: 1

hydra:
  job:
    chdir: False
